### ISSUE TITLE
Create a mailing list and add interested peoples' mail addresses

### ISSUE THREAD

**Issue by lenaschimmel** [lenaschimmel/gendentity#2]
We need a mailing list. @coopdot has started something and documented it at [[Mailing List]] but it seems like we should go for Riseup.

I think that @stymy has already collected mail addresses. As I have no other way of contacting Aimi, I hope that mentioning here and assigning will somehow work.

I can also take over this task and create the mailing list myself if you tell me you are not already working on it.

**Comment by coopdot** [comment]
I have requested a list creation from Riseup and am waiting for it to be approved. Sorry if I stepped on anyone's toes. We need to have something working and my attempt to host it myself isn't helping.

**Comment by lenaschimmel** [comment]
Hey, don't worry. I appreciate your efforts and I am happy that now we have a list. There might be more than one valid way to do it, and it's always worth giving a try.

I just saw that the list is now open for subscription, so I wrote a message to the QFG list an will now edid the CCC wiki.

THX!
